window:
  title: Azalurg
  dimensions:
    columns: 75
    lines: 25
  padding:
    x: 7
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.9


scrolling:
  history: 10000
  multiplier: 3


font:
  normal:
    family: Anonymice Nerd Font Mono
    style:  Regular
  bold:
    family: Anonymice Nerd Font Mono
    style:  Bold
  italic:
    family: Anonymice Nerd Font Mono
    style:  MediumItalic
  bold_italic:
    family: Anonymice Nerd Font Mono
    style: BoldItalic
  size: 15.5


draw_bold_text_with_bright_colors: true

# OneDark
colors:
  primary:
    background: "#1e2127"
    # background: "#2e3440"
    foreground: "#d8dee9"
  normal:
    black: "#3b4252"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#88c0d0"
    white: "#abb2bf"
  bright:
    black: "#5c6370"
    red: "#e06c75"
    green: "#98c379"
    yellow: "#d19a66"
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#eceff4"

#colors:
#  primary:
#    background: "#11121D"
#    foreground: "#a9b1d6"
#  normal:
#    black: "#32344a"
#    red: "#f7768e"
#    green: "#9ece6a"
#    yellow: "#e0af68"
#    blue: "#7aa2f7"
#    magenta: "#ad8ee6"
#    cyan: "#449dab"
#    white: "#787c99"
#  bright:
#    black: "#444b6a"
#    red: "#ff7a93"
#    green: "#b9f27c"
#    yellow: "#ff9e64"
#    blue: "#7da6ff"
#    magenta: "#bb9af7"
#    cyan: "#0db9d7"
#    white: "#acb0d0"

selection:
  save_to_clipboard: false

shell:
  program: /usr/bin/zsh

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
