import:
  - ~/.config/alacritty/colors.yml

env:
  TERM: 'xterm-256color'

window:
  title: Azalurg
  dimensions:
    columns: 75
    lines: 25
  padding:
    x: 7
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.9			

scrolling:
  history: 1000
  multiplier: 3

font:
  normal:
    family: AnonymicePro Nerd Font Mono
    style:  Regular
  bold:
    family: AnonymicePro Nerd Font Mono
    style:  Bold
  italic:
    family: AnonymicePro Nerd Font Mono
    style:  MediumItalic
  bold_italic:
    family: AnonymicePro Nerd Font Mono
    style: BoldItalic
  size: 12

draw_bold_text_with_bright_colors: true

mouse_bindings:
  - { mouse: Middle, action: Copy }
  - { mouse: Right, action: Paste}

selection:
  save_to_clipboard: false

shell:
  program: /usr/bin/zsh

cursor:
  style: 'Beam'
  vi_mode_style: 'Underline'
