env:
  TERM: 'xterm-256color'

window:
  title: Azalurg
  dimensions:
    columns: 75
    lines: 25
  padding:
    x: 7
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.8			

scrolling:
  history: 1000
  multiplier: 3

font:
  normal:
    family: Anonymice Nerd Font Mono
    style:  Regular
  bold:
    family: Anonymice Nerd Font Mono
    style:  Bold
  italic:
    family: Anonymice Nerd Font Mono
    style:  MediumItalic
  bold_italic:
    family: Anonymice Nerd Font Mono
    style: BoldItalic
  size: 12

draw_bold_text_with_bright_colors: true

colors:
 primary:
   background: "#1e2127"
   foreground: "#e6e6fa"
 normal:
   black: "#455a64"
   red: "#f55145"
   green: "#87bf48"
   yellow: "#e9de66"
   blue: "#37a0f6"
   magenta: "#d61d8f"
   cyan: "#2cbacd"
   white: "#e6e6fa"
 bright:
   black: "#455a64"
   red: "#f55145"
   green: "#87bf48"
   yellow: "#e9de66"
   blue: "#37a0f6"
   magenta: "#d61d8f"
   cyan: "#2cbacd"
   white: "#e6e6fa"

mouse_bindings:
  - { mouse: Middle, action: Copy }
  - { mouse: Right, action: Paste}

selection:
  save_to_clipboard: false

shell:
  program: /usr/bin/zsh

cursor:
  style: 'Beam'

  vi_mode_style: 'Underline'
