colors:
 primary:
   background: "#111111"
   foreground: "#ddddff"
 normal:
   black: "#333333"
   red: "#ff7777"
   green: "#77dd77"
   yellow: "#ffff77"
   blue: "#7777ff"
   magenta: "#ff77ff"
   cyan: "#77ffff"
   white: "#eeeeee"
 bright:
   black: "#444444"
   red: "#ff4477"
   green: "#77dd44"
   yellow: "#ffff44"
   blue: "#4477ff"
   magenta: "#ff44ff"
   cyan: "#44ffff"
   white: "#ffffff"
