#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill /home/azalurg/.local/share/backgrounds/wallpaper.jpg
#udiskie &
picom &

# set monitors 
hdmi=$(xrandr -q | grep 'HDMI')
dp=$(xrandr -q | grep 'DP-2')

if [[ $hdmi = *connected* ]]; then
	xrandr --output HDMI-1 --primary
	bspc monitor HDMI-1 -d h1 h2 h3 h4 h5
fi

if [[ $dp = *connected* ]]; then
	xrandr --output DP-2 --right-of HDMI-1
	bspc monitor DP-2 -d d1 d2 d3 d4 d5
fi

if [[ $hdmi != *connected* && $dp != *connected* ]]; then
	xrandr --output eDP-1 --off
else
	bspc monitor -d I II III IV V
fi

bspc config border_width         1
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a firefox desktop='^5'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
