#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# set monitors
xrandr --output HDMI-A-0 --primary --mode 1920x1080
xrandr --output DisplayPort-0 --right-of HDMI-A-0

bspc monitor HDMI-A-0 -d     
bspc monitor DisplayPort-0 -d 1 2 3 4 5
# bspc monitor DisplayPort-0 -d     

# bsp setup
bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#111111"
bspc config focused_border_color "#4477ff"

bspc rule -a code-oss desktop='^1'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Spotify desktop='^4'
bspc rule -a Galculator state=floating

# autostart 
nm-applet --indicator &	# networt applet
$HOME/.config/polybar/launch.sh	# polybar
feh --bg-fill /usr/share/backgrounds/wallpaper.jpg	# wallpaper
picom -b &	# compositor
dunst & # notification-daemon
