#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# set monitors
xrandr --output HDMI-A-0 --primary --mode 1920x1080
xrandr --output DisplayPort-0 --right-of HDMI-A-0

bspc monitor HDMI-A-0 -d     
bspc monitor DisplayPort-0 -d 1 2 3 4 5

# bsp setup
bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a firefox desktop='^5'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# autostart 
nm-applet --indicator &	# networt applet
$HOME/.config/polybar/launch.sh	# polybar
feh --bg-fill /usr/share/backgrounds/wallpaper.jpg	# wallpaper
picom -b &	# compositor
dunst & #notification-daemon 