#!/bin/bash

theme=$1

bspc config top_padding     0
bspc config bottom_padding  0
bspc config left_padding    0
bspc config right_padding   0
bspc config window_gap      0

sh $HOME/.config/rice/themes/$theme/set
