#!/bin/bash

workdir="$HOME/.config/rice/themes/oslo"

bspc config top_padding     6
bspc config bottom_padding  6
bspc config left_padding    6
bspc config right_padding   6
bspc config window_gap      12


bspc config normal_border_color "#667755"
bspc config focused_border_color "#bbccaa"

feh --bg-fill $workdir/wallpapers/wallpaper-01.jpg $workdir/wallpapers/wallpaper-02.jpg

killall polybar
polybar -q bar1 -c $workdir/polybar/config.ini &

betterlockscreen -u $workdir/wallpapers/lockscreen-01.jpg
