#!/bin/bash

workdir="$HOME/.config/rice/themes/zion"

bspc config top_padding 0
bspc config bottom_padding 0
bspc config normal_border_color "#222222"
bspc config focused_border_color "#00DF41"

feh --bg-fill $workdir/wallpapers/wallpaper-01.jpg $workdir/wallpapers/wallpaper-02.jpg

killall polybar
polybar -q bar1 -c $workdir/polybar/config.ini &
